"""nanomodem.core — wire protocol, driver, transports, and ModemNode.

This package handles serial communication with nanomodem v3 hardware per the
user guide. No LBL positioning assumptions.
"""

from .driver import NanomodemV3Driver
from .spec import MAX_BYTES_CORRECTED, SUPPLY_VOLTAGE_SCALE, supply_voltage_volts
from .wire_types import (
    AddressSetEvent,
    BroadcastCommand,
    BroadcastCommandAckEvent,
    CommandErrorEvent,
    EchoCommand,
    EchoCommandAckEvent,
    ErrorEvent,
    LocalAckEvent,
    ModemCommand,
    ModemEvent,
    PingCommand,
    PingCommandAckEvent,
    PingTimeoutEvent,
    QualityIndicatorEvent,
    QualityQueryCommand,
    QualityRejectedEvent,
    ReceivedBroadcastEvent,
    ReceivedEvent,
    ReceivedUnicastEvent,
    RemoteVoltageQueryAckEvent,
    RemoteVoltageQueryCommand,
    RemoteVoltageResponseEvent,
    RoundtripResponseEvent,
    SetAddressCommand,
    StatusQueryCommand,
    StatusResponseEvent,
    TestBroadcastReceivedEvent,
    TestRequestAckEvent,
    TestRequestCommand,
    UnicastCommand,
    UnicastCommandAckEvent,
    UnicastWithAckCommand,
    UnicastWithAckCommandAckEvent,
    UnknownLineEvent,
)

__all__ = [
    "NanomodemV3Driver",
    "MAX_BYTES_CORRECTED",
    "SUPPLY_VOLTAGE_SCALE",
    "supply_voltage_volts",
    "ModemCommand",
    "SetAddressCommand",
    "StatusQueryCommand",
    "PingCommand",
    "RemoteVoltageQueryCommand",
    "BroadcastCommand",
    "UnicastCommand",
    "UnicastWithAckCommand",
    "TestRequestCommand",
    "EchoCommand",
    "QualityQueryCommand",
    "ModemEvent",
    "LocalAckEvent",
    "ReceivedEvent",
    "ErrorEvent",
    "PingCommandAckEvent",
    "TestRequestAckEvent",
    "BroadcastCommandAckEvent",
    "UnicastCommandAckEvent",
    "UnicastWithAckCommandAckEvent",
    "RemoteVoltageQueryAckEvent",
    "EchoCommandAckEvent",
    "QualityIndicatorEvent",
    "QualityRejectedEvent",
    "AddressSetEvent",
    "StatusResponseEvent",
    "RoundtripResponseEvent",
    "PingTimeoutEvent",
    "RemoteVoltageResponseEvent",
    "ReceivedBroadcastEvent",
    "TestBroadcastReceivedEvent",
    "ReceivedUnicastEvent",
    "CommandErrorEvent",
    "UnknownLineEvent",
]
